# Generated by Django 5.2.7 on 2025-11-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
