# Generated by Django 5.2.7 on 2025-11-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_notification_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
