# Generated by Django 5.2.3 on 2025-07-12 12:08

import mechanics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MechanicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("current_lat", models.FloatField(blank=True, null=True)),
                ("current_lng", models.FloatField(blank=True, null=True)),
                ("experience_years", models.IntegerField(default=0)),
                ("specialization", models.CharField(blank=True, max_length=100)),
                (
                    "affiliated_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mechanics.models.mechanic_doc_upload_path,
                    ),
                ),
                (
                    "license_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mechanics.models.mechanic_doc_upload_path,
                    ),
                ),
                (
                    "company_affiliation_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mechanics.models.mechanic_doc_upload_path,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
