# Generated by Django 5.2.7 on 2025-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_username_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="customer_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="customer_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
